-- Jungle Gym membership commission sync
-- Safe to run on the existing attendance/payroll Supabase project.
-- This script does not delete existing attendance or payroll records.

create extension if not exists pgcrypto;

create table if not exists public.membership_commissions (
  id bigint generated by default as identity primary key,
  source_key text not null unique,
  receipt_number text not null,
  member_name text,
  nic_number text,
  registration_type text not null,
  payment_date date not null,
  staff_name text not null,
  paid_amount numeric(12,2) not null default 0,
  commission_rate numeric(5,4) not null default 0.10,
  commission_amount numeric(12,2) not null default 0,
  is_free boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint membership_paid_amount_nonnegative check (paid_amount >= 0),
  constraint membership_commission_nonnegative check (commission_amount >= 0)
);

create index if not exists membership_commissions_payment_date_idx
  on public.membership_commissions(payment_date);

create index if not exists membership_commissions_staff_name_idx
  on public.membership_commissions(lower(staff_name));

alter table public.membership_commissions enable row level security;

drop policy if exists "Admins view membership commissions"
  on public.membership_commissions;
create policy "Admins view membership commissions"
on public.membership_commissions
for select
to authenticated
using (
  exists (
    select 1
    from public.profiles p
    where p.id = auth.uid() and p.role = 'admin'
  )
);

create table if not exists public.integration_secrets (
  service_name text primary key,
  secret_hash text not null,
  updated_at timestamptz not null default now()
);

alter table public.integration_secrets enable row level security;
revoke all on public.integration_secrets from anon, authenticated;

create or replace function public.sync_membership_commission(
  p_secret text,
  p_row jsonb
)
returns jsonb
language plpgsql
security definer
set search_path = public, extensions
as $$
declare
  v_expected_hash text;
  v_source_key text;
  v_receipt text;
  v_staff text;
  v_member_name text;
  v_nic_number text;
  v_paid numeric(12,2);
  v_is_free boolean;
  v_commission numeric(12,2);
begin
  select secret_hash
    into v_expected_hash
  from public.integration_secrets
  where service_name = 'membership_commission';

  if v_expected_hash is null
     or encode(digest(coalesce(p_secret, ''), 'sha256'), 'hex') <> v_expected_hash then
    raise exception 'Invalid membership commission sync secret';
  end if;

  v_source_key := nullif(trim(p_row ->> 'source_key'), '');
  v_receipt := nullif(trim(p_row ->> 'receipt_number'), '');
  v_staff := nullif(trim(p_row ->> 'staff_name'), '');
  v_member_name := nullif(trim(p_row ->> 'member_name'), '');
  v_nic_number := nullif(trim(p_row ->> 'nic_number'), '');
  v_paid := greatest(coalesce((p_row ->> 'paid_amount')::numeric, 0), 0);
  v_is_free := lower(coalesce(v_receipt, '')) = 'free';
  v_commission := case
    when v_is_free then 0
    else round(v_paid * 0.10, 2)
  end;

  if v_source_key is null or v_receipt is null or v_staff is null then
    raise exception 'Missing required membership commission fields';
  end if;

  insert into public.membership_commissions (
    source_key, receipt_number, registration_type, payment_date, staff_name,
    paid_amount, commission_rate, commission_amount, is_free, updated_at
  )
  values (
    v_source_key,
    v_receipt,
    v_member_name,
    v_nic_number,
    coalesce(nullif(trim(p_row ->> 'registration_type'), ''), 'Unknown'),
    (p_row ->> 'payment_date')::date,
    v_staff,
    v_paid,
    0.10,
    v_commission,
    v_is_free,
    now()
  )
  on conflict (source_key) do update set
    receipt_number = excluded.receipt_number,
    member_name = excluded.member_name,
    nic_number = excluded.nic_number,
    registration_type = excluded.registration_type,
    payment_date = excluded.payment_date,
    staff_name = excluded.staff_name,
    paid_amount = excluded.paid_amount,
    commission_rate = excluded.commission_rate,
    commission_amount = excluded.commission_amount,
    is_free = excluded.is_free,
    updated_at = now();

  return jsonb_build_object(
    'ok', true,
    'commission_amount', v_commission,
    'is_free', v_is_free
  );
end;
$$;

revoke all on function public.sync_membership_commission(text, jsonb)
  from public;
grant execute on function public.sync_membership_commission(text, jsonb)
  to anon, authenticated;

-- IMPORTANT: Before running, replace PASTE_YOUR_PRIVATE_SECRET_HERE below
-- with a private value containing at least 32 random letters/numbers.
-- Store exactly the same value in Apps Script Properties under:
-- ATTENDANCE_SYNC_SECRET
insert into public.integration_secrets (service_name, secret_hash, updated_at)
values (
  'membership_commission',
  encode(digest('PASTE_YOUR_PRIVATE_SECRET_HERE', 'sha256'), 'hex'),
  now()
)
on conflict (service_name) do update set
  secret_hash = excluded.secret_hash,
  updated_at = now();
