-- Jungle Gym Coach Payroll module
-- Run this once in Supabase SQL Editor before using the Payroll section.

create table if not exists public.coach_payroll_settings (
  coach_id uuid primary key references public.profiles(id) on delete cascade,
  base_salary numeric(12,2) not null default 0,
  scheduled_hours_month numeric(8,2) not null default 0,
  minimum_attendance_pct numeric(5,2) not null default 70,
  overtime_multiplier numeric(5,2) not null default 1.50,
  attendance_bonus_95_pct numeric(5,2) not null default 10.00,
  attendance_bonus_90_pct numeric(5,2) not null default 5.00,
  short_notice_allowance numeric(12,2) not null default 500,
  team_support_threshold integer not null default 3,
  team_support_bonus numeric(12,2) not null default 1000,
  active boolean not null default true,
  updated_at timestamptz not null default now(),
  constraint payroll_base_salary_nonnegative check (base_salary >= 0),
  constraint payroll_scheduled_hours_nonnegative check (scheduled_hours_month >= 0),
  constraint payroll_min_attendance_range check (minimum_attendance_pct between 0 and 100),
  constraint payroll_overtime_multiplier_positive check (overtime_multiplier > 0)
);

create table if not exists public.shift_covers (
  id bigint generated by default as identity primary key,
  covering_coach_id uuid not null references public.profiles(id) on delete cascade,
  absent_coach_id uuid not null references public.profiles(id) on delete cascade,
  cover_date date not null,
  cover_hours numeric(6,2) not null,
  short_notice boolean not null default false,
  approved boolean not null default true,
  notes text,
  created_at timestamptz not null default now(),
  constraint shift_cover_hours_positive check (cover_hours > 0),
  constraint shift_cover_different_coaches check (covering_coach_id <> absent_coach_id)
);

create index if not exists shift_covers_cover_date_idx
  on public.shift_covers(cover_date);

create index if not exists shift_covers_covering_coach_idx
  on public.shift_covers(covering_coach_id);

alter table public.coach_payroll_settings enable row level security;
alter table public.shift_covers enable row level security;

drop policy if exists "Admins manage payroll settings" on public.coach_payroll_settings;
create policy "Admins manage payroll settings"
on public.coach_payroll_settings
for all
to authenticated
using (
  exists (
    select 1
    from public.profiles p
    where p.id = auth.uid() and p.role = 'admin'
  )
)
with check (
  exists (
    select 1
    from public.profiles p
    where p.id = auth.uid() and p.role = 'admin'
  )
);

drop policy if exists "Admins manage shift covers" on public.shift_covers;
create policy "Admins manage shift covers"
on public.shift_covers
for all
to authenticated
using (
  exists (
    select 1
    from public.profiles p
    where p.id = auth.uid() and p.role = 'admin'
  )
)
with check (
  exists (
    select 1
    from public.profiles p
    where p.id = auth.uid() and p.role = 'admin'
  )
);

-- Initial values use the salary/hour terms supplied by Jungle Gym.
-- They remain editable from the Payroll section.
insert into public.coach_payroll_settings (coach_id, base_salary, scheduled_hours_month)
select
  p.id,
  case
    when lower(p.full_name) like 'chaminda%' then 40000
    when lower(p.full_name) like 'devon%' then 20000
    when lower(p.full_name) like 'malika%' then 20000
    when lower(p.full_name) like 'harshana%' then 20000
    else 0
  end,
  case
    when lower(p.full_name) like 'chaminda%' then 224
    when lower(p.full_name) like 'devon%' then 64
    when lower(p.full_name) like 'malika%' then 144
    when lower(p.full_name) like 'harshana%' then 110
    else 0
  end
from public.profiles p
where p.role = 'coach'
on conflict (coach_id) do nothing;


-- Membership sales commission integration
-- New memberships and renewals earn 10% for the selected staff member.
-- A receipt number equal to "free" (case-insensitive) earns zero commission.
-- Apps Script staff name "Alpha" is mapped to payroll coach "Harshana" by the web app.
create extension if not exists pgcrypto;

create table if not exists public.membership_commissions (
  id bigint generated by default as identity primary key,
  source_key text not null unique,
  receipt_number text not null,
  registration_type text not null,
  payment_date date not null,
  staff_name text not null,
  paid_amount numeric(12,2) not null default 0,
  commission_rate numeric(5,4) not null default 0.10,
  commission_amount numeric(12,2) not null default 0,
  is_free boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint membership_paid_amount_nonnegative check (paid_amount >= 0),
  constraint membership_commission_nonnegative check (commission_amount >= 0)
);

create index if not exists membership_commissions_payment_date_idx
  on public.membership_commissions(payment_date);

create index if not exists membership_commissions_staff_name_idx
  on public.membership_commissions(lower(staff_name));

alter table public.membership_commissions enable row level security;

drop policy if exists "Admins view membership commissions"
  on public.membership_commissions;
create policy "Admins view membership commissions"
on public.membership_commissions
for select
to authenticated
using (
  exists (
    select 1
    from public.profiles p
    where p.id = auth.uid() and p.role = 'admin'
  )
);

create table if not exists public.integration_secrets (
  service_name text primary key,
  secret_hash text not null,
  updated_at timestamptz not null default now()
);

alter table public.integration_secrets enable row level security;
revoke all on public.integration_secrets from anon, authenticated;

create or replace function public.sync_membership_commission(
  p_secret text,
  p_row jsonb
)
returns jsonb
language plpgsql
security definer
set search_path = public, extensions
as $$
declare
  v_expected_hash text;
  v_source_key text;
  v_receipt text;
  v_staff text;
  v_paid numeric(12,2);
  v_is_free boolean;
  v_commission numeric(12,2);
begin
  select secret_hash
    into v_expected_hash
  from public.integration_secrets
  where service_name = 'membership_commission';

  if v_expected_hash is null
     or encode(digest(coalesce(p_secret, ''), 'sha256'), 'hex') <> v_expected_hash then
    raise exception 'Invalid membership commission sync secret';
  end if;

  v_source_key := nullif(trim(p_row ->> 'source_key'), '');
  v_receipt := nullif(trim(p_row ->> 'receipt_number'), '');
  v_staff := nullif(trim(p_row ->> 'staff_name'), '');
  v_paid := greatest(coalesce((p_row ->> 'paid_amount')::numeric, 0), 0);
  v_is_free := lower(coalesce(v_receipt, '')) = 'free';
  v_commission := case
    when v_is_free then 0
    else round(v_paid * 0.10, 2)
  end;

  if v_source_key is null or v_receipt is null or v_staff is null then
    raise exception 'Missing required membership commission fields';
  end if;

  insert into public.membership_commissions (
    source_key,
    receipt_number,
    registration_type,
    payment_date,
    staff_name,
    paid_amount,
    commission_rate,
    commission_amount,
    is_free,
    updated_at
  )
  values (
    v_source_key,
    v_receipt,
    coalesce(nullif(trim(p_row ->> 'registration_type'), ''), 'Unknown'),
    (p_row ->> 'payment_date')::date,
    v_staff,
    v_paid,
    0.10,
    v_commission,
    v_is_free,
    now()
  )
  on conflict (source_key) do update set
    receipt_number = excluded.receipt_number,
    registration_type = excluded.registration_type,
    payment_date = excluded.payment_date,
    staff_name = excluded.staff_name,
    paid_amount = excluded.paid_amount,
    commission_rate = excluded.commission_rate,
    commission_amount = excluded.commission_amount,
    is_free = excluded.is_free,
    updated_at = now();

  return jsonb_build_object(
    'ok', true,
    'commission_amount', v_commission,
    'is_free', v_is_free
  );
end;
$$;

revoke all on function public.sync_membership_commission(text, jsonb)
  from public;
grant execute on function public.sync_membership_commission(text, jsonb)
  to anon, authenticated;

-- ONE-TIME SECRET SETUP
-- Replace CHANGE_THIS_TO_A_LONG_RANDOM_SECRET with a private value of at least
-- 32 characters, run this statement in Supabase, then store the same value in
-- Google Apps Script Properties as ATTENDANCE_SYNC_SECRET.
-- Never commit the real secret to GitHub.
--
-- insert into public.integration_secrets (service_name, secret_hash, updated_at)
-- values (
--   'membership_commission',
--   encode(digest('CHANGE_THIS_TO_A_LONG_RANDOM_SECRET', 'sha256'), 'hex'),
--   now()
-- )
-- on conflict (service_name) do update set
--   secret_hash = excluded.secret_hash,
--   updated_at = now();
