-- Jungle Gym Coach Payroll module
-- Run this once in Supabase SQL Editor before using the Payroll section.

create table if not exists public.coach_payroll_settings (
  coach_id uuid primary key references public.profiles(id) on delete cascade,
  base_salary numeric(12,2) not null default 0,
  scheduled_hours_month numeric(8,2) not null default 0,
  minimum_attendance_pct numeric(5,2) not null default 70,
  overtime_multiplier numeric(5,2) not null default 1.50,
  attendance_bonus_95_pct numeric(5,2) not null default 10.00,
  attendance_bonus_90_pct numeric(5,2) not null default 5.00,
  short_notice_allowance numeric(12,2) not null default 500,
  team_support_threshold integer not null default 3,
  team_support_bonus numeric(12,2) not null default 1000,
  active boolean not null default true,
  updated_at timestamptz not null default now(),
  constraint payroll_base_salary_nonnegative check (base_salary >= 0),
  constraint payroll_scheduled_hours_nonnegative check (scheduled_hours_month >= 0),
  constraint payroll_min_attendance_range check (minimum_attendance_pct between 0 and 100),
  constraint payroll_overtime_multiplier_positive check (overtime_multiplier > 0)
);

create table if not exists public.shift_covers (
  id bigint generated by default as identity primary key,
  covering_coach_id uuid not null references public.profiles(id) on delete cascade,
  absent_coach_id uuid not null references public.profiles(id) on delete cascade,
  cover_date date not null,
  cover_hours numeric(6,2) not null,
  short_notice boolean not null default false,
  approved boolean not null default true,
  notes text,
  created_at timestamptz not null default now(),
  constraint shift_cover_hours_positive check (cover_hours > 0),
  constraint shift_cover_different_coaches check (covering_coach_id <> absent_coach_id)
);

create index if not exists shift_covers_cover_date_idx
  on public.shift_covers(cover_date);

create index if not exists shift_covers_covering_coach_idx
  on public.shift_covers(covering_coach_id);

alter table public.coach_payroll_settings enable row level security;
alter table public.shift_covers enable row level security;

drop policy if exists "Admins manage payroll settings" on public.coach_payroll_settings;
create policy "Admins manage payroll settings"
on public.coach_payroll_settings
for all
to authenticated
using (
  exists (
    select 1
    from public.profiles p
    where p.id = auth.uid() and p.role = 'admin'
  )
)
with check (
  exists (
    select 1
    from public.profiles p
    where p.id = auth.uid() and p.role = 'admin'
  )
);

drop policy if exists "Admins manage shift covers" on public.shift_covers;
create policy "Admins manage shift covers"
on public.shift_covers
for all
to authenticated
using (
  exists (
    select 1
    from public.profiles p
    where p.id = auth.uid() and p.role = 'admin'
  )
)
with check (
  exists (
    select 1
    from public.profiles p
    where p.id = auth.uid() and p.role = 'admin'
  )
);

-- Initial values use the salary/hour terms supplied by Jungle Gym.
-- They remain editable from the Payroll section.
insert into public.coach_payroll_settings (coach_id, base_salary, scheduled_hours_month)
select
  p.id,
  case
    when lower(p.full_name) like 'chaminda%' then 40000
    when lower(p.full_name) like 'devon%' then 20000
    when lower(p.full_name) like 'malika%' then 20000
    when lower(p.full_name) like 'harshana%' then 20000
    else 0
  end,
  case
    when lower(p.full_name) like 'chaminda%' then 224
    when lower(p.full_name) like 'devon%' then 64
    when lower(p.full_name) like 'malika%' then 144
    when lower(p.full_name) like 'harshana%' then 110
    else 0
  end
from public.profiles p
where p.role = 'coach'
on conflict (coach_id) do nothing;
